import type { Metadata } from "next";
import Navbar from "../_components/Navbar";
import Footer from "../_components/Footer";
import { NotificationProvider } from "../_context/NotificationContext";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function NavFooterLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<NotificationProvider>
			<div>
				<Navbar />
				<main className="mt-20 overflow-x-hidden min-h-screen">{children}</main>
				<Footer />
			</div>
		</NotificationProvider>
	);
}
