import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import localFont from "next/font/local";
import { AuthProvider } from "./_context/AuthContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const FuturaPTBold = localFont({
  src: [
    {
      path: "../public/fonts/FuturaPT-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-futura-pt-bold",
});
const FuturaPTLight = localFont({
  src: [
    {
      path: "../public/fonts/FuturaPT-Light.woff2",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-futura-pt-light",
});
const FuturaPTMedium = localFont({
  src: [
    {
      path: "../public/fonts/FuturaPT-Medium.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-futura-pt-medium",
});
const FuturaPTBook = localFont({
  src: [
    {
      path: "../public/fonts/FuturaPT-Book.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-futura-pt-book",
});
const FuturaPTHeavy = localFont({
  src: [
    {
      path: "../public/fonts/FuturaPT-Heavy.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-futura-pt-heavy",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <head>
        {/* FontAwesome CDN */}
        <title>FoodShare - Plateforme de Dons Alimentaires</title>
        <meta
          name="description"
          content="Plateforme alimentaire pour favoriser l'accès à une alimentation saine et durable"
        />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${FuturaPTBold.variable} ${FuturaPTLight.variable} ${FuturaPTMedium.variable} ${FuturaPTBook.variable} ${FuturaPTHeavy.variable} antialiased`}
      >
        <AuthProvider>
          {children}
          <Toaster
            toastOptions={{
              unstyled: true,
              classNames: {
                error:
                  "flex items-center gap-2 rounded-md bg-red-400 text-white font-futuraPTBook py-3 px-4",
                success:
                  "flex items-center gap-2 rounded-md  text-green-400 text-white font-futuraPTBook py-3 px-4",
                warning:
                  "flex items-center gap-2 rounded-md text-yellow-400 text-white font-futuraPTBook py-3 px-4",
                info: "flex items-center gap-2 rounded-md bg-blue-400 text-white font-futuraPTBook py-3 px-4",
              },
            }}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
