import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import localFont from "next/font/local";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const FuturaPTBold = localFont({
  src: [
    {
      path: "../public/fonts/FuturaPT-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-futura-pt-bold",
});
const FuturaPTLight = localFont({
  src: [
    {
      path: "../public/fonts/FuturaPT-Light.woff2",
      weight: "300",
      style: "normal",
    },
  ],
  variable: "--font-futura-pt-light",
});
const FuturaPTMedium = localFont({
  src: [
    {
      path: "../public/fonts/FuturaPT-Medium.woff2",
      weight: "500",
      style: "normal",
    },
  ],
  variable: "--font-futura-pt-medium",
});
const FuturaPTBook = localFont({
  src: [
    {
      path: "../public/fonts/FuturaPT-Book.woff2",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-futura-pt-book",
});
const FuturaPTHeavy = localFont({
  src: [
    {
      path: "../public/fonts/FuturaPT-Heavy.woff2",
      weight: "800",
      style: "normal",
    },
  ],
  variable: "--font-futura-pt-heavy",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${FuturaPTBold.variable} ${FuturaPTLight.variable} ${FuturaPTMedium.variable} ${FuturaPTBook.variable} ${FuturaPTHeavy.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
